/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author camac2045
 */
public class MagicalMethodsFrom extends javax.swing.JFrame {

    /**
     * Creates new form MagicalMethodsFrom
     */
    public MagicalMethodsFrom() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        larInput2 = new javax.swing.JTextField();
        larInput1 = new javax.swing.JTextField();
        smallInput2 = new javax.swing.JTextField();
        smallInput1 = new javax.swing.JTextField();
        powInput2 = new javax.swing.JTextField();
        powInput1 = new javax.swing.JTextField();
        hypoInput1 = new javax.swing.JTextField();
        hypoInput2 = new javax.swing.JTextField();
        roundUpInput = new javax.swing.JTextField();
        roundDownInput = new javax.swing.JTextField();
        squareInput = new javax.swing.JTextField();
        radiansInput = new javax.swing.JTextField();
        largest = new javax.swing.JButton();
        power = new javax.swing.JButton();
        smallest = new javax.swing.JButton();
        hypo = new javax.swing.JButton();
        roundUp = new javax.swing.JButton();
        roundDown = new javax.swing.JButton();
        square = new javax.swing.JButton();
        radians = new javax.swing.JButton();
        larOutput = new javax.swing.JLabel();
        smallOutput = new javax.swing.JLabel();
        powOutput = new javax.swing.JLabel();
        hypoOutput = new javax.swing.JLabel();
        roundDownOutput = new javax.swing.JLabel();
        roundUpOutput = new javax.swing.JLabel();
        squareOutput = new javax.swing.JLabel();
        radiansOutput = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 51, 102));

        jLabel1.setFont(new java.awt.Font("Rockwell", 0, 28)); // NOI18N
        jLabel1.setText("Magical Math Methods");

        jLabel2.setFont(new java.awt.Font("Rockwell", 0, 12)); // NOI18N
        jLabel2.setText("Enter two numbers and click the button. The program will display the largest of the numbers.");

        jLabel3.setFont(new java.awt.Font("Rockwell", 0, 12)); // NOI18N
        jLabel3.setText("Enter two numbers and click the button. The program will display the smallest of the numbers.");

        jLabel4.setFont(new java.awt.Font("Rockwell", 0, 12)); // NOI18N
        jLabel4.setText("Enter two numbers and click the button. The program will display the first number to the power of the second.");

        jLabel5.setFont(new java.awt.Font("Rockwell", 0, 12)); // NOI18N
        jLabel5.setText("Enter two sidelengths of a right angle and click the button. The program will display the hypotaneuse of the triangle.");

        jLabel6.setFont(new java.awt.Font("Rockwell", 0, 12)); // NOI18N
        jLabel6.setText("Enter a decimal value and click the button. The program will display the value rounded up.");

        jLabel7.setFont(new java.awt.Font("Rockwell", 0, 12)); // NOI18N
        jLabel7.setText("Enter a decimal value and click the button. The program will display the value rounded down.");

        jLabel8.setFont(new java.awt.Font("Rockwell", 0, 12)); // NOI18N
        jLabel8.setText("Enter an integer. The program will display the square root.");

        jLabel9.setFont(new java.awt.Font("Rockwell", 0, 12)); // NOI18N
        jLabel9.setText("Enter an angle in degrees. The program will display the angle in radians.");

        larInput2.setText("0");
        larInput2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                larInput2ActionPerformed(evt);
            }
        });

        larInput1.setText("0");
        larInput1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                larInput1ActionPerformed(evt);
            }
        });

        smallInput2.setText("0");
        smallInput2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                smallInput2ActionPerformed(evt);
            }
        });

        smallInput1.setText("0");
        smallInput1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                smallInput1ActionPerformed(evt);
            }
        });

        powInput2.setText("0");
        powInput2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                powInput2ActionPerformed(evt);
            }
        });

        powInput1.setText("0");
        powInput1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                powInput1ActionPerformed(evt);
            }
        });

        hypoInput1.setText("0");
        hypoInput1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hypoInput1ActionPerformed(evt);
            }
        });

        hypoInput2.setText("0");
        hypoInput2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hypoInput2ActionPerformed(evt);
            }
        });

        roundUpInput.setText("0");
        roundUpInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                roundUpInputActionPerformed(evt);
            }
        });

        roundDownInput.setText("0");
        roundDownInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                roundDownInputActionPerformed(evt);
            }
        });

        squareInput.setText("0");
        squareInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                squareInputActionPerformed(evt);
            }
        });

        radiansInput.setText("0");
        radiansInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radiansInputActionPerformed(evt);
            }
        });

        largest.setText("Largest");
        largest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                largestActionPerformed(evt);
            }
        });

        power.setText("Power");
        power.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                powerActionPerformed(evt);
            }
        });

        smallest.setText("Smallest");
        smallest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                smallestActionPerformed(evt);
            }
        });

        hypo.setText("Hypotaneuse");
        hypo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hypoActionPerformed(evt);
            }
        });

        roundUp.setText("Round Up");
        roundUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                roundUpActionPerformed(evt);
            }
        });

        roundDown.setText("Round Down");
        roundDown.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                roundDownActionPerformed(evt);
            }
        });

        square.setText("Square Root");
        square.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                squareActionPerformed(evt);
            }
        });

        radians.setText("Radians");
        radians.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radiansActionPerformed(evt);
            }
        });

        larOutput.setFont(new java.awt.Font("Rockwell", 0, 12)); // NOI18N
        larOutput.setForeground(new java.awt.Color(51, 51, 255));
        larOutput.setText("The Larger Number is:");

        smallOutput.setFont(new java.awt.Font("Rockwell", 0, 12)); // NOI18N
        smallOutput.setForeground(new java.awt.Color(51, 51, 255));
        smallOutput.setText("The smallest Number is:");

        powOutput.setFont(new java.awt.Font("Rockwell", 0, 12)); // NOI18N
        powOutput.setForeground(new java.awt.Color(51, 51, 255));
        powOutput.setText("The answer is:");

        hypoOutput.setFont(new java.awt.Font("Rockwell", 0, 12)); // NOI18N
        hypoOutput.setForeground(new java.awt.Color(51, 51, 255));
        hypoOutput.setText("The length of the hypotaneuse is:");

        roundDownOutput.setFont(new java.awt.Font("Rockwell", 0, 12)); // NOI18N
        roundDownOutput.setForeground(new java.awt.Color(51, 51, 255));
        roundDownOutput.setText("The rounded number is:");

        roundUpOutput.setFont(new java.awt.Font("Rockwell", 0, 12)); // NOI18N
        roundUpOutput.setForeground(new java.awt.Color(51, 51, 255));
        roundUpOutput.setText("The rounded number is:");

        squareOutput.setFont(new java.awt.Font("Rockwell", 0, 12)); // NOI18N
        squareOutput.setForeground(new java.awt.Color(51, 51, 255));
        squareOutput.setText("The square root is:");

        radiansOutput.setFont(new java.awt.Font("Rockwell", 0, 12)); // NOI18N
        radiansOutput.setForeground(new java.awt.Color(51, 51, 255));
        radiansOutput.setText("The angle in radians is:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel4))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap(33, Short.MAX_VALUE)
                        .addComponent(jLabel5))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(133, 133, 133)
                        .addComponent(powInput1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(powInput2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(129, 129, 129)
                        .addComponent(power)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(powOutput, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addGap(35, 35, 35))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 442, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(141, 141, 141))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(131, 131, 131)
                        .addComponent(hypoInput1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(hypoInput2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(130, 130, 130)
                        .addComponent(hypo)
                        .addGap(26, 26, 26)
                        .addComponent(hypoOutput, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(187, 187, 187)
                                .addComponent(jLabel1))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(70, 70, 70)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 536, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 536, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(88, 88, 88)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(181, 181, 181)
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(134, 134, 134)
                                .addComponent(smallInput1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(smallInput2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(127, 127, 127)
                                .addComponent(smallest))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addGap(164, 164, 164)
                                    .addComponent(radiansInput, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(153, 153, 153)
                                    .addComponent(radians)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(radiansOutput, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addGap(161, 161, 161)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(squareInput, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(157, 157, 157)
                                            .addComponent(square)
                                            .addGap(46, 46, 46)
                                            .addComponent(squareOutput, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(roundDownInput, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(158, 158, 158)
                                            .addComponent(roundDown)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(roundDownOutput, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(161, 161, 161)
                                    .addComponent(roundUpInput, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(157, 157, 157)
                                    .addComponent(roundUp)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(roundUpOutput, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(56, 56, 56))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(smallOutput, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(133, 133, 133)
                        .addComponent(larInput1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(larInput2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(124, 124, 124)
                        .addComponent(largest)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(larOutput, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(53, 53, 53))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addGap(13, 13, 13)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(larInput2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(larInput1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(largest)
                    .addComponent(larOutput))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(smallInput2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(smallInput1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(smallest)
                    .addComponent(smallOutput))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(powInput1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(powInput2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(power)
                    .addComponent(powOutput))
                .addGap(10, 10, 10)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hypoInput1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hypoInput2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hypo)
                    .addComponent(hypoOutput))
                .addGap(7, 7, 7)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(roundUpInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(roundUp)
                    .addComponent(roundUpOutput))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(roundDownInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(roundDown)
                    .addComponent(roundDownOutput))
                .addGap(6, 6, 6)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(squareInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(square)
                    .addComponent(squareOutput))
                .addGap(9, 9, 9)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radiansInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(radians)
                    .addComponent(radiansOutput))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void larInput2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_larInput2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_larInput2ActionPerformed

    private void larInput1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_larInput1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_larInput1ActionPerformed

    private void smallInput2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_smallInput2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_smallInput2ActionPerformed

    private void smallInput1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_smallInput1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_smallInput1ActionPerformed

    private void powInput2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_powInput2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_powInput2ActionPerformed

    private void powInput1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_powInput1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_powInput1ActionPerformed

    private void hypoInput1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hypoInput1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hypoInput1ActionPerformed

    private void hypoInput2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hypoInput2ActionPerformed
        
    }//GEN-LAST:event_hypoInput2ActionPerformed

    private void roundUpInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_roundUpInputActionPerformed
        
    }//GEN-LAST:event_roundUpInputActionPerformed

    private void roundDownInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_roundDownInputActionPerformed
        
    }//GEN-LAST:event_roundDownInputActionPerformed

    private void squareInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_squareInputActionPerformed
        
    }//GEN-LAST:event_squareInputActionPerformed

    private void radiansInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radiansInputActionPerformed
        
    }//GEN-LAST:event_radiansInputActionPerformed

    private void largestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_largestActionPerformed
        int largeOne, largeTwo;
        largeOne = Integer.parseInt(larInput1.getText());
        largeTwo = Integer.parseInt(larInput2.getText());
        larOutput.setText("The larger number is: "+Math.max(largeOne, largeTwo));
    }//GEN-LAST:event_largestActionPerformed

    private void hypoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hypoActionPerformed
        int num1, num2;
        num1 = Integer.parseInt(hypoInput1.getText());
        num2 = Integer.parseInt(hypoInput2.getText());
        hypoOutput.setText("The length of the hypotaneuse is: "+Math.hypot(num1, num2));
    }//GEN-LAST:event_hypoActionPerformed

    private void radiansActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radiansActionPerformed
        int radians;
        radians = Integer.parseInt(radiansInput.getText());
        radiansOutput.setText("The degree in radians is: "+Math.toRadians(radians));
    }//GEN-LAST:event_radiansActionPerformed

    private void squareActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_squareActionPerformed
        int square;
        square = Integer.parseInt(squareInput.getText());
        squareOutput.setText("The square root of the number is: "+Math.sqrt(square));
    }//GEN-LAST:event_squareActionPerformed

    private void roundDownActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_roundDownActionPerformed
        double roundDown;
        roundDown = Double.parseDouble(roundDownInput.getText());
        roundDownOutput.setText("Rounded down "+Math.floor(roundDown));
    }//GEN-LAST:event_roundDownActionPerformed

    private void roundUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_roundUpActionPerformed
        double roundUp;
        roundUp = Double.parseDouble(roundUpInput.getText());
        System.out.println(Math.ceil(roundUp));
        roundUpOutput.setText("Rounded up "+Math.ceil(roundUp));
    }//GEN-LAST:event_roundUpActionPerformed

    private void powerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_powerActionPerformed
        int num1, num2;
        num1 = Integer.parseInt(powInput1.getText());
        num2 = Integer.parseInt(powInput2.getText());
        powOutput.setText("The answer is: "+Math.pow(num1, num2));
    }//GEN-LAST:event_powerActionPerformed

    private void smallestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_smallestActionPerformed
        int num1, num2;
        num1 = Integer.parseInt(smallInput1.getText());
        num2 = Integer.parseInt(smallInput2.getText());
        smallOutput.setText("The smaller number is: "+Math.min(num1, num2));
    }//GEN-LAST:event_smallestActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MagicalMethodsFrom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MagicalMethodsFrom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MagicalMethodsFrom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MagicalMethodsFrom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MagicalMethodsFrom().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton hypo;
    private javax.swing.JTextField hypoInput1;
    private javax.swing.JTextField hypoInput2;
    private javax.swing.JLabel hypoOutput;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField larInput1;
    private javax.swing.JTextField larInput2;
    private javax.swing.JLabel larOutput;
    private javax.swing.JButton largest;
    private javax.swing.JTextField powInput1;
    private javax.swing.JTextField powInput2;
    private javax.swing.JLabel powOutput;
    private javax.swing.JButton power;
    private javax.swing.JButton radians;
    private javax.swing.JTextField radiansInput;
    private javax.swing.JLabel radiansOutput;
    private javax.swing.JButton roundDown;
    private javax.swing.JTextField roundDownInput;
    private javax.swing.JLabel roundDownOutput;
    private javax.swing.JButton roundUp;
    private javax.swing.JTextField roundUpInput;
    private javax.swing.JLabel roundUpOutput;
    private javax.swing.JTextField smallInput1;
    private javax.swing.JTextField smallInput2;
    private javax.swing.JLabel smallOutput;
    private javax.swing.JButton smallest;
    private javax.swing.JButton square;
    private javax.swing.JTextField squareInput;
    private javax.swing.JLabel squareOutput;
    // End of variables declaration//GEN-END:variables
}
